import { Layout } from "@/components/Layout";
import Image from "next/image";

/**
 * カルネアサダのレシピ
 */
export default function CarneAsada() {
  return (
    <Layout>
      <section>
        <h1>カルネアサダ</h1>
        <Image
          src="/images/recipe/carne_asada/hero.jpg"
          width={1508}
          height={640}
          alt=""
        />
      </section>
      <section>
        <h1>生地づくり</h1>
        <p>マサハリナを使う</p>
        <Image
          src="/images/recipe/carne_asada/1-1.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <p>マサハリナ130gに水150mlを入れて混ぜる（塩も適量）</p>
        <Image
          src="/images/recipe/carne_asada/1-2.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <p>指で潰した時に生地が割れるか割れないかくらいがちょうど良い</p>
        <Image
          src="/images/recipe/carne_asada/1-3.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <p>
          こねたら大体2,30分寝かせ、20gずつ、14等分にして焼く
          <br />
          個人的には薄いほうが美味しかったので20gでなるべく薄めがちょうどよかった
        </p>
      </section>
      <section>
        <h1>生地づくり</h1>
        <p>マサハリナを使う</p>
        <Image
          src="/images/recipe/carne_asada/2-1.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <Image
          src="/images/recipe/carne_asada/2-2.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <Image
          src="/images/recipe/carne_asada/2-3.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <Image
          src="/images/recipe/carne_asada/2-4.jpg"
          width={1508}
          height={640}
          alt=""
        />
      </section>
      <section>
        <h1>生地づくり</h1>
        <p>マサハリナを使う</p>
        <Image
          src="/images/recipe/carne_asada/3-1.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <Image
          src="/images/recipe/carne_asada/3-2.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <Image
          src="/images/recipe/carne_asada/3-3.jpg"
          width={1508}
          height={640}
          alt=""
        />
      </section>
      <section>
        <h1>生地づくり</h1>
        <p>マサハリナを使う</p>
        <Image
          src="/images/recipe/carne_asada/4-1.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <Image
          src="/images/recipe/carne_asada/4-2.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <Image
          src="/images/recipe/carne_asada/4-3.jpg"
          width={1508}
          height={640}
          alt=""
        />
      </section>
      <section>
        <h1>生地づくり</h1>
        <p>マサハリナを使う</p>
        <Image
          src="/images/recipe/carne_asada/5-1.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <Image
          src="/images/recipe/carne_asada/5-2.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <Image
          src="/images/recipe/carne_asada/5-3.jpg"
          width={1508}
          height={640}
          alt=""
        />
        <Image
          src="/images/recipe/carne_asada/5-4.jpg"
          width={1508}
          height={640}
          alt=""
        />
      </section>
      <section>
        <h1>完成</h1>
        <Image
          src="/images/recipe/carne_asada/complete.jpg"
          width={1508}
          height={640}
          alt=""
        />
      </section>
    </Layout>
  );
}
